### ISSUE TITLE
Awaiting mapException?

### ISSUE THREAD

**Issue by masterwok** [definitelyokay/app_http_client#1]
Hey, great article! I was looking through your code and I noticed that `AppHttpClient` isn't awaiting the calls to `_mapException`. Shouldn't these be awaited? 

https://github.com/definitelyokay/app_http_client/blob/d34e92cd24083c73643b30dd8f2c73145684ffaa/lib/src/app_http_client_base.dart#L38

**Comment by jolexxa** [comment]
I don't think so :)) `_mapException` also returns a `Future<Response<T>>` so it is just passed through. The caller of either function can choose to `await` if desired, or use the more traditional future API's.

**Comment by masterwok** [comment]
Oh, sweet! Thanks for the clarification! I didn't realize Dart would properly execute an async function in this fashion. Good to know going forward. Thanks again!
